version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PORT: 5000
    volumes:
      # Main code
      - ./project:/app/project
      # PostgreSQL
      - ./db.env:/app/db.env
      # sqlite
      - ./instance:/app/instance
      # Flask-Migrate
      - ./migrations:/app/migrations
    ports:
      - 5000:5000
    restart: on-failure

  pgsql:
    image: postgres
    restart: on-failure
    # When both env_file and environment are set for a service, values set by environment have precedence.
    environment:
      PGDATA: /var/lib/postgresql/data
      # Use external file instead of hardcoded password
      # https://github.com/docker-library/postgres/issues/111#issuecomment-293053904
      # POSTGRES_PASSWORD: example
      # error: both POSTGRES_PASSWORD and POSTGRES_PASSWORD_FILE are set (but are exclusive)
      # https://github.com/nextcloud/docker/issues/270#issuecomment-396222239
      # POSTGRES_PASSWORD_FILE: /run/secrets/postgres_db_password
    # secrets:
    #   - postgres_db_password
    env_file:
      - db.env
    # https://github.com/nextcloud/docker/issues/385#issuecomment-403379480
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    # TODO: maybe there are some default environment variable that can set default password etc.
    # https://github.com/michalhosna/adminer-docker
    # https://github.com/wodby/adminer
    restart: on-failure
    ports:
      - 8080:8080

# secrets:
#   postgres_db_password:
#     # Create and modify password in `secrets/postgress_db_password`
#     file: ./secrets/postgress_db_password
